### PR TITLE
docs.rs improvements

### PR DESCRIPTION
**Pull request by Icelk**
Enables tags of which features are needed to enable functionality in docs.rs.

Also fixed a small typo in build.rs.

### CODE REVIEW

**Comment by Yuri6037** [comment]
Thank you for your PR, I will merge this asap once the last typo is fixed as well.

**Comment by Icelk** [comment]
@Yuri6037 I just fixed the last typo.

**Comment by Yuri6037** [comment]
You still didn't fix the missing 'a' in "Failed".

**Comment by Icelk** [comment]
Done now.

**Comment by Yuri6037** [comment]
Thank you

**Comment by Icelk** [comment]
Thank you for this project. It's awesome!

**Pull request merged**
